library fireschema_dart_runtime;

/// Support for the FireSchema Dart runtime.
///
/// Exports base classes used by code generated by the FireSchema CLI.
export 'src/types.dart';

// Export base classes
export 'src/base_collection_ref.dart';
export 'src/base_query_builder.dart';
export 'src/base_update_builder.dart';

// Re-export common Firestore types? Optional, might be convenient for generated code.
// export 'package:cloud_firestore/cloud_firestore.dart'
//     show
//         FirebaseFirestore,
//         CollectionReference,
//         DocumentReference,
//         DocumentSnapshot,
//         QuerySnapshot,
//         Query,
//         Timestamp,
//         GeoPoint,
//         FieldValue,
//         SetOptions;
