# .github/workflows/publish.yml in fireschema_dart_runtime repo
name: Publish Dart Runtime

on:
  push:
    branches:
      - main # Temporarily trigger on main branch pushes for testing
    # tags:
    #   - 'v*.*.*' # Original trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for publishing to pub.dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Flutter environment (includes Dart)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or the channel your package supports

      - name: Install dependencies
        run: flutter pub get

      # Optional: Analyze code
      - name: Analyze project source
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      # Install Firebase CLI (needed for emulator)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Start Firestore Emulator
      - name: Start Firestore Emulator
        run: |
          nohup firebase emulators:start --only firestore --project=demo-project-id &
          sleep 10 # Wait for emulator to start

      # Run tests
      - name: Run tests
        run: flutter test --platform vm # Specify VM platform for integration tests

      # Publish package to pub.dev
      # Ensure PUB_DEV_PUBLISH_ACCESS_TOKEN, PUB_DEV_PUBLISH_REFRESH_TOKEN, 
      # and PUB_DEV_PUBLISH_ID_TOKEN are configured as secrets in the repository settings.
      # See: https://github.com/marketplace/actions/publish-dart-flutter-package
      - name: Publish to pub.dev
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          accessToken: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          idToken: ${{ secrets.PUB_DEV_PUBLISH_ID_TOKEN }}
          # Optional: Use 'flutter pub publish --dry-run' first for testing
          # dryRun: true 
          # Optional: Skip validation checks if needed (not recommended)
          # skipValidation: true
